### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by SteveTheDog**
add spongooo boi to thingy and add description

### CODE REVIEW

**Comment by sponges** [comment]
cannot accept this because you are white

**Comment by SteveTheDog** [comment]
wow !!!

**Comment by sponges** [comment]
yep this is a racist discord bot

**Comment by SteveTheDog** [comment]
Ur not my president!!!

**Comment by sponges** [comment]
ur not my son..

**Comment by bramhaag** [comment]
ur not my father

**Comment by sponges** [comment]
stay out of this bram..

**Comment by bramhaag** [comment]
holy shit webhooks are fast

**Comment by SteveTheDog** [comment]
hello bram butt out this is between me and sexybacon so either put ur butt out or make better pr than me... !!!!

**Comment by sponges** [comment]
YEAHHHHHHHH BUTT OUT BRAM !!!!!!!!!!!!!!!!!!!!

**Comment by SteveTheDog** [comment]
G E T  T O L D

**Pull request closed without merging**
